
package com.certus.facturehoy.ws2.cfdi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "KeyStoreException", targetNamespace = "http://cfdi.ws2.facturehoy.certus.com/")
public class KeyStoreException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private KeyStoreException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public KeyStoreException_Exception(String message, KeyStoreException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public KeyStoreException_Exception(String message, KeyStoreException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.certus.facturehoy.ws2.cfdi.KeyStoreException
     */
    public KeyStoreException getFaultInfo() {
        return faultInfo;
    }

}
