
package com.certus.facturehoy.ws2.cfdi;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsEmisionTimbrado", targetNamespace = "http://cfdi.ws2.facturehoy.certus.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsEmisionTimbrado {


    /**
     * 
     * @param usuario
     * @param contrasenia
     * @param idServicio
     * @param xml
     * @return
     *     returns com.certus.facturehoy.ws2.cfdi.WsResponseBO
     */
    @WebMethod(operationName = "EmitirTimbrar")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "EmitirTimbrar", targetNamespace = "http://cfdi.ws2.facturehoy.certus.com/", className = "com.certus.facturehoy.ws2.cfdi.EmitirTimbrar")
    @ResponseWrapper(localName = "EmitirTimbrarResponse", targetNamespace = "http://cfdi.ws2.facturehoy.certus.com/", className = "com.certus.facturehoy.ws2.cfdi.EmitirTimbrarResponse")
    @Action(input = "http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado/EmitirTimbrarRequest", output = "http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado/EmitirTimbrarResponse")
    public WsResponseBO emitirTimbrar(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia,
        @WebParam(name = "idServicio", targetNamespace = "")
        int idServicio,
        @WebParam(name = "xml", targetNamespace = "")
        byte[] xml);

    /**
     * 
     * @param usuario
     * @param contrasenia
     * @param keyEncode
     * @param uuid
     * @return
     *     returns com.certus.facturehoy.ws2.cfdi.WsResponseBO
     */
    @WebMethod(operationName = "Cancelar")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Cancelar", targetNamespace = "http://cfdi.ws2.facturehoy.certus.com/", className = "com.certus.facturehoy.ws2.cfdi.Cancelar")
    @ResponseWrapper(localName = "CancelarResponse", targetNamespace = "http://cfdi.ws2.facturehoy.certus.com/", className = "com.certus.facturehoy.ws2.cfdi.CancelarResponse")
    @Action(input = "http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado/CancelarRequest", output = "http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado/CancelarResponse")
    public WsResponseBO cancelar(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia,
        @WebParam(name = "UUID", targetNamespace = "")
        List<String> uuid,
        @WebParam(name = "keyEncode", targetNamespace = "")
        String keyEncode);

    /**
     * 
     * @param usuario
     * @param contrasenia
     * @param uuid
     * @return
     *     returns com.certus.facturehoy.ws2.cfdi.WsResponseBO
     */
    @WebMethod(operationName = "RecuperarAcuse")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RecuperarAcuse", targetNamespace = "http://cfdi.ws2.facturehoy.certus.com/", className = "com.certus.facturehoy.ws2.cfdi.RecuperarAcuse")
    @ResponseWrapper(localName = "RecuperarAcuseResponse", targetNamespace = "http://cfdi.ws2.facturehoy.certus.com/", className = "com.certus.facturehoy.ws2.cfdi.RecuperarAcuseResponse")
    @Action(input = "http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado/RecuperarAcuseRequest", output = "http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado/RecuperarAcuseResponse")
    public WsResponseBO recuperarAcuse(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia,
        @WebParam(name = "UUID", targetNamespace = "")
        String uuid);

}
