
package com.certus.facturehoy.ws2.cfdi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WsServiciosService", targetNamespace = "http://cfdi.ws2.facturehoy.certus.com/", wsdlLocation = "http://66.225.192.223:8080/CFDI/WsServicios?wsdl")
public class WsServiciosService
    extends Service
{

    private final static URL WSSERVICIOSSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSSERVICIOSSERVICE_EXCEPTION;
    private final static QName WSSERVICIOSSERVICE_QNAME = new QName("http://cfdi.ws2.facturehoy.certus.com/", "WsServiciosService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://66.225.192.223:8080/CFDI/WsServicios?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSSERVICIOSSERVICE_WSDL_LOCATION = url;
        WSSERVICIOSSERVICE_EXCEPTION = e;
    }

    public WsServiciosService() {
        super(__getWsdlLocation(), WSSERVICIOSSERVICE_QNAME);
    }

    public WsServiciosService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSSERVICIOSSERVICE_QNAME, features);
    }

    public WsServiciosService(URL wsdlLocation) {
        super(wsdlLocation, WSSERVICIOSSERVICE_QNAME);
    }

    public WsServiciosService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSSERVICIOSSERVICE_QNAME, features);
    }

    public WsServiciosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsServiciosService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsServicios
     */
    @WebEndpoint(name = "WsServiciosPort")
    public WsServicios getWsServiciosPort() {
        return super.getPort(new QName("http://cfdi.ws2.facturehoy.certus.com/", "WsServiciosPort"), WsServicios.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsServicios
     */
    @WebEndpoint(name = "WsServiciosPort")
    public WsServicios getWsServiciosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cfdi.ws2.facturehoy.certus.com/", "WsServiciosPort"), WsServicios.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSSERVICIOSSERVICE_EXCEPTION!= null) {
            throw WSSERVICIOSSERVICE_EXCEPTION;
        }
        return WSSERVICIOSSERVICE_WSDL_LOCATION;
    }

}
