
package com.certus.facturehoy.ws2.cfdi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsServicios", targetNamespace = "http://cfdi.ws2.facturehoy.certus.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsServicios {


    /**
     * 
     * @param usuario
     * @param contrasenia
     * @return
     *     returns com.certus.facturehoy.ws2.cfdi.WsServicioBO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerServicios", targetNamespace = "http://cfdi.ws2.facturehoy.certus.com/", className = "com.certus.facturehoy.ws2.cfdi.ObtenerServicios")
    @ResponseWrapper(localName = "obtenerServiciosResponse", targetNamespace = "http://cfdi.ws2.facturehoy.certus.com/", className = "com.certus.facturehoy.ws2.cfdi.ObtenerServiciosResponse")
    @Action(input = "http://cfdi.ws2.facturehoy.certus.com/WsServicios/obtenerServiciosRequest", output = "http://cfdi.ws2.facturehoy.certus.com/WsServicios/obtenerServiciosResponse")
    public WsServicioBO obtenerServicios(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

}
